#!/bin/bash
#
# Generate proper versioning include file
#
CURDATE=$(date +%Y\/%m\/%d\ %H:%M:%S)
CURVERS=$(grep 'PACKAGE_VERSION' dkms.conf | sed -e 's/^.*=//' -e 's/"//g')

echo "#define	NETATOPVERSION	\"$CURVERS\""	 > netatopversion.h
echo "#define	NETATOPDATE	\"$CURDATE\""	>> netatopversion.h
